/*
    IB_ga_final_param.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 16/07/2015 11:10:40.767
    source model: IB_ga_final
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "IB_ga_final_param.h"

/* Variable definitions */

const volatile GAREAL m = 1.14;
const volatile GAREAL a1 = (-1.125);
const volatile GAREAL a2 = 0.006971153846154;
const volatile GAREAL a3 = 1.116071428571428;
const volatile GAREAL a4 = 0.006473214285714;
const volatile GAREAL a5 = (-0.034934497816594);
const volatile GAREAL b1 = 96.153846153846146;
const volatile GAREAL b2 = 89.285714285714292;
/*  INTEGRAL BACKSTEPPING CONTROLLER CONSTANTS  */
const volatile GAREAL b3 = 43.668122270742359;
const volatile GAREAL Tca1 = 0.01;
const volatile GAREAL Tca2 = 0.01;
const volatile GAREAL Tca3 = 0.01;
const volatile GAREAL Tcx1 = 0.01;
const volatile GAREAL Tcx2 = 0.01;
const volatile GAREAL Tcx3 = 0.01;
const volatile GAREAL Tcy1 = 0.01;
/*  0.01  */
const volatile GAREAL Tcy2 = 0.05;
const volatile GAREAL Tcy3 = 0.02;
const volatile GAREAL Tcr1 = 0.01;
const volatile GAREAL Tcr2 = 0.05;
const volatile GAREAL Tcr3 = 0.01;
const volatile GAREAL Tcp1 = 0.01;
const volatile GAREAL Tcp2 = 0.05;
const volatile GAREAL Tcp3 = 0.01;
const volatile GAREAL Tcyw1 = 0.01;
const volatile GAREAL Tcyw2 = 0.05;
/*  spring phi  */
const volatile GAREAL Tcyw3 = 0.01;
/*  damper phi  */
const volatile GAUINT8 c1 = 15;
/*  spring theta  */
const volatile GAUINT8 c2 = 6;
/*  damper theta  */
const volatile GAUINT8 c3 = 15;
/*  spring psi  */
const volatile GAUINT8 c4 = 6;
/*  damper psi  */
const volatile GAUINT8 c5 = 10;
/*  spring Z  */
const volatile GAUINT8 c6 = 5;
/*  damper Z  */
const volatile GAREAL c7 = 3.5;
/*  spring X  */
const volatile GAREAL c8 = 1.5;
/*  damper X  */
const volatile GAUINT8 c9 = 10;
/*  spring Y  */
const volatile GAREAL c10 = 1.5;
/*  damper Y  */
const volatile GAUINT8 c11 = 10;
/*  "mass" phi  */
const volatile GAREAL c12 = 1.5;
/*  "mass" theta  */
const volatile GAREAL ld1 = 0.07;
/*  "mass" psi  */
const volatile GAREAL ld2 = 0.05;
/*  "mass" Z  */
const volatile GAREAL ld3 = 0.01;
/*  "mass" X  */
const volatile GAREAL ld4 = 0.01;
/*  "mass" Y  */
const volatile GAREAL ld5 = 0.001;
const volatile GAREAL ld6 = 0.001;
const volatile GAREAL fr_a = 55.434782608695649;
const volatile GAREAL fr_b = (-0.630434782608696);
const volatile GAREAL fr2_a = 55.434782608695649;
const volatile GAREAL fr2_b = (-0.630434782608696);
const volatile GAREAL theta_saturation = 0.523598775598299;
const volatile GAREAL phi_saturation = 0.523598775598299;
const volatile GAREAL f_a = 36.786648751856305;
const volatile GAREAL f_b = 0.760200834453009;
const volatile GAREAL f_c = (-0.125238667703840);
const volatile GAREAL fIn_a = 1.207583625166043E-4;
const volatile GAREAL fIn_b = 2.415167250332085E-4;
const volatile GAREAL fIn_c = 1.207583625166043E-4;
const volatile GAREAL fIn_d = (-1.956043956043956);
const volatile GAREAL fIn_e = 0.956526989494022;
const volatile GAUINT8 freq = 60;
const volatile GAUINT8 b0_bp = 0;
const volatile GAUINT32 b1_bp = 115600;
const volatile GAUINT8 b2_bp = 0;
const volatile GAUINT8 a0_bp = 1;
const volatile GAUINT16 a1_bp = 1768;
const volatile GAUINT32 a2_bp = 115600;
const volatile GAUINT8 b0_lp = 0;
const volatile GAUINT8 b1_lp = 0;
const volatile GAUINT8 b2_lp = 1;
const volatile GAUINT8 a0_lp = 1;
const volatile GAUINT8 a1_lp = 1;
const volatile GAUINT8 a2_lp = 1;
