/*
    X_POSITION_CONTROL_nIB.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 16/07/2015 11:10:40.829
    source model: IB_ga_final
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "X_POSITION_CONTROL_nIB.h"

/* Variable definitions */

GAUINT8 i1_1;

/* Function definitions */

void X_POSITION_CONTROL_IB_init(t_IB_ga_final_state *_state_) {
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_10 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_11 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_12 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_9 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_10 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_11 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_10 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_13 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_11 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_12 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_13 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_8 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_9 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_10 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
}

void X_POSITION_CONTROL_IB_compute(t_X_POSITION_CONTROL_IB_io *_io_, t_IB_ga_final_state *_state_) {
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=U1>/<OutDataPort: name=>  */
    GAREAL U1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=x>/<OutDataPort: name=>  */
    GAREAL x;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=xd>/<OutDataPort: name=>  */
    GAREAL xd;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=fcs>/<OutDataPort: name=>  */
    GAREAL fcs[6];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=x_consts>/<OutDataPort: name=>  */
    GAREAL x_consts[3];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL Switch5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL e10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add4>/<OutDataPort: name=>  */
    GAREAL e9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL c9_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL c10_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL ld5_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_20;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_19;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_21;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_22;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_23;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_24;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux>/<OutDataPort: name=>  */
    GAREAL Mux[3];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux1>/<OutDataPort: name=>  */
    GAREAL Mux1[2];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux2>/<OutDataPort: name=>  */
    GAREAL Mux2[5];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux3>/<OutDataPort: name=>  */
    GAREAL Mux3[2];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL thetad;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_58;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_57;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_59;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_60;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_61;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product3>/<OutDataPort: name=>  */
    GAREAL Product3_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product4>/<OutDataPort: name=>  */
    GAREAL Product4_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL xddot_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum3>/<OutDataPort: name=>  */
    GAREAL Sum3_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_62;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_63;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_64;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_65;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_66;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product3>/<OutDataPort: name=>  */
    GAREAL Product3_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product4>/<OutDataPort: name=>  */
    GAREAL Product4_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL xddotdot;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum3>/<OutDataPort: name=>  */
    GAREAL Sum3_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_67;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_68;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_69;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_70;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_71;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_16;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product3>/<OutDataPort: name=>  */
    GAREAL Product3_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product4>/<OutDataPort: name=>  */
    GAREAL Product4_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL xdot;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum3>/<OutDataPort: name=>  */
    GAREAL Sum3_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_16;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_17;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL X5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_72;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_73;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_74;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_25;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_26;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_17;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_18;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn2>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn2>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_27;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_28;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Math\nFunction>/<OutDataPort: name=>  */
    GAREAL Math_Function;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_18;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_29;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_30;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_19;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_31;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_32;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_20;
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    Constant_2 = theta_saturation;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<SourceBlock: name=Constant>  */
    Constant_3 = 1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn2>/<SourceBlock: name=Constant>  */
    Constant_1 = m;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn2>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_11 = _state_->Unit_Delay2_memory_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_10 = _state_->Unit_Delay2_memory_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_12 = _state_->Unit_Delay2_memory_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_10 = _state_->Unit_Delay7_memory_9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_9 = _state_->Unit_Delay7_memory_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_11 = _state_->Unit_Delay7_memory_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>  */
    Gain2 = -1 * Constant_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=x>  */
    x = _io_->x;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=x>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_13 = _state_->Unit_Delay1_memory_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_13 = _state_->Unit_Delay2_memory_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=xd>  */
    xd = _io_->xd;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=xd>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add4>  */
    e9 = xd - x;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=U1>  */
    U1 = _io_->U1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=U1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn2>/<CombinatorialBlock: name=Divide>  */
    Divide = 1.0 / U1 * Constant_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn2>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_11 = _state_->Unit_Delay1_memory_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_10 = _state_->Unit_Delay1_memory_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_12 = _state_->Unit_Delay1_memory_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_9 = _state_->Unit_Delay8_memory_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_8 = _state_->Unit_Delay8_memory_9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_10 = _state_->Unit_Delay8_memory_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=fcs>  */
    for (i1_1 = 0; i1_1 < 6; i1_1++) {
        fcs[i1_1] = _io_->fcs[i1_1];
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=fcs>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=x_consts>  */
    for (i1_1 = 0; i1_1 < 3; i1_1++) {
        x_consts[i1_1] = _io_->x_consts[i1_1];
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=x_consts>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux1>  */
    Demux1_20 = fcs[0];
    Demux1_19 = fcs[1];
    Demux1_21 = fcs[2];
    Demux1_22 = fcs[3];
    Demux1_23 = fcs[4];
    Demux1_24 = fcs[5];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product1>  */
    Product1_17 = Demux1_24 * e9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product>  */
    Product_16 = Unit_Delay1_13 * Demux1_24;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum>  */
    Sum_14 = Product1_17 + Product_16;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum1>  */
    X5 = Sum_14 - Unit_Delay2_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux2>  */
    Mux2[0] = Demux1_20;
    Mux2[1] = Demux1_19;
    Mux2[2] = Demux1_21;
    Mux2[3] = Demux1_22;
    Mux2[4] = Demux1_23;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>  */
    Demux_58 = Mux2[0];
    Demux_57 = Mux2[1];
    Demux_59 = Mux2[2];
    Demux_60 = Mux2[3];
    Demux_61 = Mux2[4];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product4>  */
    Product4_11 = Unit_Delay2_11 * Demux_57;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product2>  */
    Product2_12 = Unit_Delay7_10 * Demux_60;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product>  */
    Product_12 = xd * Demux_58;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product1>  */
    Product1_13 = Unit_Delay1_11 * Demux_59;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum3>  */
    Sum3_11 = Product4_11 + Product1_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>  */
    Sum_12 = Product_12 + Sum3_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product3>  */
    Product3_12 = Unit_Delay8_9 * Demux_61;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>  */
    Sum2_11 = Product3_12 + Product2_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    xddot_4 = Sum_12 - Sum2_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux>  */
    Mux[0] = e9;
    Mux[1] = xddot_4;
    Mux[2] = X5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux>  */
    Demux_72 = Mux[0];
    Demux_73 = Mux[1];
    Demux_74 = Mux[2];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>  */
    Demux_62 = Mux2[0];
    Demux_63 = Mux2[1];
    Demux_64 = Mux2[2];
    Demux_65 = Mux2[3];
    Demux_66 = Mux2[4];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product4>  */
    Product4_10 = Unit_Delay2_10 * Demux_63;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product2>  */
    Product2_11 = Unit_Delay7_9 * Demux_65;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product1>  */
    Product1_15 = Unit_Delay1_10 * Demux_64;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum3>  */
    Sum3_10 = Product4_10 + Product1_15;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product3>  */
    Product3_11 = Unit_Delay8_8 * Demux_66;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>  */
    Sum2_10 = Product3_11 + Product2_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product>  */
    Product_14 = xddot_4 * Demux_62;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>  */
    Sum_11 = Product_14 + Sum3_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    xddotdot = Sum_11 - Sum2_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>  */
    Demux_67 = Mux2[0];
    Demux_68 = Mux2[1];
    Demux_69 = Mux2[2];
    Demux_70 = Mux2[3];
    Demux_71 = Mux2[4];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product4>  */
    Product4_12 = Unit_Delay2_12 * Demux_68;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product2>  */
    Product2_13 = Unit_Delay7_11 * Demux_70;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product>  */
    Product_15 = x * Demux_67;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product1>  */
    Product1_16 = Unit_Delay1_12 * Demux_69;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum3>  */
    Sum3_12 = Product4_12 + Product1_16;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum>  */
    Sum_13 = Product_15 + Sum3_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product3>  */
    Product3_13 = Unit_Delay8_10 * Demux_71;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum2>  */
    Sum2_12 = Product3_13 + Product2_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum1>  */
    xdot = Sum_13 - Sum2_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux>  */
    c9_1 = x_consts[0];
    c10_1 = x_consts[1];
    ld5_1 = x_consts[2];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux1>  */
    Mux1[0] = c9_1;
    Mux1[1] = c10_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Demux1>  */
    Demux1_29 = Mux1[0];
    Demux1_30 = Mux1[1];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Add2>  */
    Add2_4 = Demux1_29 + Demux1_30;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux3>  */
    Mux3[0] = c9_1;
    Mux3[1] = ld5_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Demux1>  */
    Demux1_31 = Mux3[0];
    Demux1_32 = Mux3[1];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux1>  */
    Demux1_25 = Mux3[0];
    Demux1_26 = Mux3[1];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Demux1>  */
    Demux1_27 = Mux3[0];
    Demux1_28 = Mux3[1];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Math\nFunction>  */
    Math_Function = Demux1_27 * Demux1_27;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Math\nFunction>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Add2>  */
    Add2_3 = Constant_3 - Math_Function + Demux1_28;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Product>  */
    Product_18 = Add2_3 * e9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope1>  */
    _state_->Scope1_memory_2 = Product_18;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Product>  */
    Product_20 = Demux1_31 * Demux1_32 * X5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope>  */
    _state_->Scope_memory_3 = Product_20;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product>  */
    Product_17 = Demux1_25 * Demux_72;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product1>  */
    Product1_18 = Demux1_26 * Demux_74;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Add>  */
    Add = Product_17 + Demux_73 + Product1_18;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add1>  */
    e10 = Add - xdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Product>  */
    Product_19 = Add2_4 * e10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope3>  */
    _state_->Scope3_memory_1 = Product_19;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add2>  */
    Add2_1 = Product_18 + Product_19 - Product_20 + xddotdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Product2>  */
    thetad = Divide * Add2_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4 = thetad > Constant_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    Product_13 = Relational_Operator4 * Constant_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5 = thetad < Gain2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    Product1_14 = Relational_Operator5 * Constant_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>  */
    Gain3 = -1 * Product1_14;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    Add2_2 = Product_13 + Gain3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    if (Add2_2 != 0) {
        Switch5 = Add2_2;
    } else {
        Switch5 = thetad;
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SinkBlock: name=thetad>  */
    _io_->thetad = Switch5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SinkBlock: name=thetad>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_10 = Unit_Delay7_11;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_9 = Unit_Delay7_9;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_8 = Unit_Delay7_10;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_13 = Unit_Delay2_12;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_12 = Unit_Delay2_10;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_11 = Unit_Delay2_11;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_13 = X5;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_10 = e9;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_11 = xdot;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_10 = xddotdot;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_9 = xddot_4;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_12 = x;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_11 = xddot_4;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_10 = xd;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
}

