/*
    Y_POSITION_CONTROL_nIB.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 16/07/2015 11:10:40.880
    source model: IB_ga_final
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "Y_POSITION_CONTROL_nIB.h"

/* Variable definitions */

GAUINT8 i1_3;

/* Function definitions */

void Y_POSITION_CONTROL_IB_init(t_IB_ga_final_state *_state_) {
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_14 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_15 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_16 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_12 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_13 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_14 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_14 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_17 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_15 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_16 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_17 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_11 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_12 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_13 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
}

void Y_POSITION_CONTROL_IB_compute(t_Y_POSITION_CONTROL_IB_io *_io_, t_IB_ga_final_state *_state_) {
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=U1>/<OutDataPort: name=>  */
    GAREAL U1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=y>/<OutDataPort: name=>  */
    GAREAL y;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=yd>/<OutDataPort: name=>  */
    GAREAL yd;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=fcs>/<OutDataPort: name=>  */
    GAREAL fcs[6];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=y_consts>/<OutDataPort: name=>  */
    GAREAL y_consts[3];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_22;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_20;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL Switch5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL e11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL e12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL c11_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL c12_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL ld6_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_34;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_33;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_35;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_36;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_37;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_38;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux>/<OutDataPort: name=>  */
    GAREAL Mux[3];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux2>/<OutDataPort: name=>  */
    GAREAL Mux2[5];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux3>/<OutDataPort: name=>  */
    GAREAL Mux3[2];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux4>/<OutDataPort: name=>  */
    GAREAL Mux4[2];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_76;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_75;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_77;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_78;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_79;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_21;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_19;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product3>/<OutDataPort: name=>  */
    GAREAL Product3_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product4>/<OutDataPort: name=>  */
    GAREAL Product4_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_16;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL Sum1_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum3>/<OutDataPort: name=>  */
    GAREAL Sum3_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_80;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_81;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_82;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_83;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_84;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_23;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_21;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2_16;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product3>/<OutDataPort: name=>  */
    GAREAL Product3_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product4>/<OutDataPort: name=>  */
    GAREAL Product4_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL yddotdot;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum3>/<OutDataPort: name=>  */
    GAREAL Sum3_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_85;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_86;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_87;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_88;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_89;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_24;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_22;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2_17;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product3>/<OutDataPort: name=>  */
    GAREAL Product3_16;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product4>/<OutDataPort: name=>  */
    GAREAL Product4_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_17;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL Sum1_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum3>/<OutDataPort: name=>  */
    GAREAL Sum3_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_16;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_16;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_25;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_23;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_18;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL X6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_17;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_17;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_39;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_40;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_41;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux2>/<OutDataPort: name=>  */
    GAREAL Demux2_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux2>/<OutDataPort: name=>  */
    GAREAL Demux2_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_26;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_24;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn2>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn2>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn2>/<CombinatorialBlock: name=Gain>/<OutDataPort: name=>  */
    GAREAL Gain;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Demux2>/<OutDataPort: name=>  */
    GAREAL Demux2_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Demux2>/<OutDataPort: name=>  */
    GAREAL Demux2_9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Math\nFunction>/<OutDataPort: name=>  */
    GAREAL Math_Function;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_27;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Demux2>/<OutDataPort: name=>  */
    GAREAL Demux2_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Demux2>/<OutDataPort: name=>  */
    GAREAL Demux2_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_28;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Demux2>/<OutDataPort: name=>  */
    GAREAL Demux2_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Demux2>/<OutDataPort: name=>  */
    GAREAL Demux2_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_29;
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    Constant_5 = phi_saturation;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<SourceBlock: name=Constant>  */
    Constant_6 = 1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=y>  */
    y = _io_->y;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=y>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=yd>  */
    yd = _io_->yd;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=yd>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add>  */
    e11 = yd - y;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn2>/<SourceBlock: name=Constant>  */
    Constant_4 = m;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn2>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_15 = _state_->Unit_Delay2_memory_14;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_14 = _state_->Unit_Delay2_memory_15;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_16 = _state_->Unit_Delay2_memory_16;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn2>/<CombinatorialBlock: name=Gain>  */
    Gain = -1 * Constant_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn2>/<CombinatorialBlock: name=Gain>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_13 = _state_->Unit_Delay7_memory_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_12 = _state_->Unit_Delay7_memory_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_14 = _state_->Unit_Delay7_memory_14;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=U1>  */
    U1 = _io_->U1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=U1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn2>/<CombinatorialBlock: name=Divide>  */
    Divide = 1.0 / U1 * Gain;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn2>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope5>  */
    _state_->Scope5_memory = Divide;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>  */
    Gain2 = -1 * Constant_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=fcs>  */
    for (i1_3 = 0; i1_3 < 6; i1_3++) {
        fcs[i1_3] = _io_->fcs[i1_3];
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=fcs>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_17 = _state_->Unit_Delay1_memory_14;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_17 = _state_->Unit_Delay2_memory_17;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=y_consts>  */
    for (i1_3 = 0; i1_3 < 3; i1_3++) {
        y_consts[i1_3] = _io_->y_consts[i1_3];
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SourceBlock: name=y_consts>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_15 = _state_->Unit_Delay1_memory_15;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_14 = _state_->Unit_Delay1_memory_16;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_16 = _state_->Unit_Delay1_memory_17;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_12 = _state_->Unit_Delay8_memory_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_11 = _state_->Unit_Delay8_memory_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_13 = _state_->Unit_Delay8_memory_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux1>  */
    Demux1_34 = fcs[0];
    Demux1_33 = fcs[1];
    Demux1_35 = fcs[2];
    Demux1_36 = fcs[3];
    Demux1_37 = fcs[4];
    Demux1_38 = fcs[5];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product>  */
    Product_25 = Demux1_38 * e11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product1>  */
    Product1_23 = Unit_Delay1_17 * Demux1_38;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum>  */
    Sum_18 = Product_25 + Product1_23;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum1>  */
    X6 = Sum_18 - Unit_Delay2_17;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux2>  */
    Mux2[0] = Demux1_34;
    Mux2[1] = Demux1_33;
    Mux2[2] = Demux1_35;
    Mux2[3] = Demux1_36;
    Mux2[4] = Demux1_37;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>  */
    Demux_76 = Mux2[0];
    Demux_75 = Mux2[1];
    Demux_77 = Mux2[2];
    Demux_78 = Mux2[3];
    Demux_79 = Mux2[4];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product>  */
    Product_21 = yd * Demux_76;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product4>  */
    Product4_14 = Unit_Delay2_15 * Demux_75;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product2>  */
    Product2_14 = Unit_Delay7_13 * Demux_78;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product1>  */
    Product1_19 = Unit_Delay1_15 * Demux_77;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum3>  */
    Sum3_14 = Product4_14 + Product1_19;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>  */
    Sum_16 = Product_21 + Sum3_14;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product3>  */
    Product3_15 = Unit_Delay8_12 * Demux_79;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Product3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>  */
    Sum2_14 = Product3_15 + Product2_14;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    Sum1_11 = Sum_16 - Sum2_14;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux>  */
    Mux[0] = e11;
    Mux[1] = Sum1_11;
    Mux[2] = X6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux1>  */
    Demux1_39 = Mux[0];
    Demux1_40 = Mux[1];
    Demux1_41 = Mux[2];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope4>  */
    _state_->Scope4_memory_1 = Sum1_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>  */
    Demux_80 = Mux2[0];
    Demux_81 = Mux2[1];
    Demux_82 = Mux2[2];
    Demux_83 = Mux2[3];
    Demux_84 = Mux2[4];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product4>  */
    Product4_13 = Unit_Delay2_14 * Demux_81;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product2>  */
    Product2_16 = Unit_Delay7_12 * Demux_83;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product1>  */
    Product1_21 = Unit_Delay1_14 * Demux_82;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum3>  */
    Sum3_13 = Product4_13 + Product1_21;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product3>  */
    Product3_14 = Unit_Delay8_11 * Demux_84;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>  */
    Sum2_13 = Product3_14 + Product2_16;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product>  */
    Product_23 = Sum1_11 * Demux_80;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>  */
    Sum_15 = Product_23 + Sum3_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    yddotdot = Sum_15 - Sum2_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope6>  */
    _state_->Scope6_memory = yddotdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope6>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>  */
    Demux_85 = Mux2[0];
    Demux_86 = Mux2[1];
    Demux_87 = Mux2[2];
    Demux_88 = Mux2[3];
    Demux_89 = Mux2[4];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product>  */
    Product_24 = y * Demux_85;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product4>  */
    Product4_15 = Unit_Delay2_16 * Demux_86;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product2>  */
    Product2_17 = Unit_Delay7_14 * Demux_88;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product1>  */
    Product1_22 = Unit_Delay1_16 * Demux_87;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum3>  */
    Sum3_15 = Product4_15 + Product1_22;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum>  */
    Sum_17 = Product_24 + Sum3_15;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product3>  */
    Product3_16 = Unit_Delay8_13 * Demux_89;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Product3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum2>  */
    Sum2_15 = Product3_16 + Product2_17;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum1>  */
    Sum1_10 = Sum_17 - Sum2_15;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope2>  */
    _state_->Scope2_memory_2 = Sum1_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux>  */
    c11_1 = y_consts[0];
    c12_1 = y_consts[1];
    ld6_3 = y_consts[2];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux3>  */
    Mux3[0] = c11_1;
    Mux3[1] = c12_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Demux2>  */
    Demux2_10 = Mux3[0];
    Demux2_11 = Mux3[1];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Demux2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Add2>  */
    Add2_8 = Demux2_10 + Demux2_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux4>  */
    Mux4[0] = c11_1;
    Mux4[1] = ld6_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Demux2>  */
    Demux2_12 = Mux4[0];
    Demux2_13 = Mux4[1];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Demux2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux2>  */
    Demux2_7 = Mux4[0];
    Demux2_6 = Mux4[1];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Demux2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Demux2>  */
    Demux2_8 = Mux4[0];
    Demux2_9 = Mux4[1];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Demux2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Math\nFunction>  */
    Math_Function = Demux2_8 * Demux2_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Math\nFunction>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Add2>  */
    Add2_7 = Constant_6 - Math_Function + Demux2_9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Product>  */
    Product_27 = Add2_7 * e11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn3>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope1>  */
    _state_->Scope1_memory_3 = Product_27;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Product>  */
    Product_29 = Demux2_12 * Demux2_13 * X6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn5>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope>  */
    _state_->Scope_memory_4 = Product_29;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product>  */
    Product_26 = Demux2_7 * Demux1_39;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product1>  */
    Product1_24 = Demux2_6 * Demux1_41;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Add>  */
    Add = Product_26 + Demux1_40 + Product1_24;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn1>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add1>  */
    e12 = Add - Sum1_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Product>  */
    Product_28 = Add2_8 * e12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=fn4>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope3>  */
    _state_->Scope3_memory_2 = Product_28;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add2>  */
    Add2_5 = Product_27 + Product_28 - Product_29 + yddotdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Product2>  */
    Product2_15 = Divide * Add2_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4 = Product2_15 > Constant_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    Product_22 = Relational_Operator4 * Constant_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5 = Product2_15 < Gain2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    Product1_20 = Relational_Operator5 * Constant_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>  */
    Gain3 = -1 * Product1_20;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    Add2_6 = Product_22 + Gain3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    if (Add2_6 != 0) {
        Switch5 = Add2_6;
    } else {
        Switch5 = Product2_15;
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SinkBlock: name=phid>  */
    _io_->phid = Switch5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SinkBlock: name=phid>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_13 = Unit_Delay7_14;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_12 = Unit_Delay7_12;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_11 = Unit_Delay7_13;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_17 = Unit_Delay2_16;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_16 = Unit_Delay2_14;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_15 = Unit_Delay2_15;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_17 = X6;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_14 = e11;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator 1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_14 = Sum1_10;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_13 = yddotdot;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_12 = Sum1_11;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_16 = y;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn4>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_15 = Sum1_11;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_14 = yd;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
}

