/*
    Controller_phi.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 13/02/2014 16:04:13.393
    source model: PIDcontroller
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "Controller_phi.h"

/* Function definitions */

void Controller_phi_init(t_PIDcontroller_state *_state_) {
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator1>  */
    _state_->Unit_Delay_Integrator1_memory_1 = 0;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator1>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator>  */
    _state_->Unit_Delay_Integrator_memory_1 = 0;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<SequentialBlock: name=Unit_Delay_Derivative>  */
    _state_->Unit_Delay_Derivative_memory_1 = 0;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<SequentialBlock: name=Unit_Delay_Derivative>  */
}

void Controller_phi_compute(t_Controller_phi_io *_io_, t_PIDcontroller_state *_state_) {
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=dt>/<OutDataPort: name=>  */
    GAREAL dt;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=u>/<OutDataPort: name=>  */
    GAREAL u;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=Kp>/<OutDataPort: name=>  */
    GAREAL Kp;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=Ki>/<OutDataPort: name=>  */
    GAREAL Ki;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=Kd>/<OutDataPort: name=>  */
    GAREAL Kd;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide_4;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Divide1>/<OutDataPort: name=>  */
    GAREAL Divide1;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Divide2>/<OutDataPort: name=>  */
    GAREAL Divide2;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL Add1;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<CombinatorialBlock: name=Multiply>/<OutDataPort: name=>  */
    GAREAL Multiply;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator>/<OutDataPort: name=>  */
    GAREAL Unit_Delay_Integrator;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay_Integrator1;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide_3;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<CombinatorialBlock: name=Subtract1>/<OutDataPort: name=>  */
    GAREAL Subtract1;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<SequentialBlock: name=Unit_Delay_Derivative>/<OutDataPort: name=>  */
    GAREAL Unit_Delay_Derivative;
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=dt>  */
    dt = _io_->dt;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=dt>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SourceBlock: name=Constant>  */
    Constant = 0.5;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=u>  */
    u = _io_->u;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=u>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator1>  */
    Unit_Delay_Integrator1 = _state_->Unit_Delay_Integrator1_memory_1;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator1>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator>  */
    Unit_Delay_Integrator = _state_->Unit_Delay_Integrator_memory_1;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=Kp>  */
    Kp = _io_->Kp;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=Kp>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Divide>  */
    Divide_4 = u * Kp;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<SequentialBlock: name=Unit_Delay_Derivative>  */
    Unit_Delay_Derivative = _state_->Unit_Delay_Derivative_memory_1;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<SequentialBlock: name=Unit_Delay_Derivative>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=Ki>  */
    Ki = _io_->Ki;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=Ki>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Divide1>  */
    Divide1 = Divide_4 * Ki;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Divide1>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<CombinatorialBlock: name=Add1>  */
    Add1 = Divide1 + Unit_Delay_Integrator1;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<CombinatorialBlock: name=Multiply>  */
    Multiply = dt * Constant * Add1;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<CombinatorialBlock: name=Multiply>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<CombinatorialBlock: name=Add>  */
    Add = Multiply + Unit_Delay_Integrator;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=Kd>  */
    Kd = _io_->Kd;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SourceBlock: name=Kd>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Divide2>  */
    Divide2 = Divide_4 * Kd;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Divide2>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<CombinatorialBlock: name=Subtract1>  */
    Subtract1 = Divide2 - Unit_Delay_Derivative;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<CombinatorialBlock: name=Subtract1>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<CombinatorialBlock: name=Divide>  */
    Divide_3 = Subtract1 / dt;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Sum>  */
    Sum = Divide_4 + Add + Divide_3;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SinkBlock: name=y>  */
    _io_->y = Sum;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SinkBlock: name=y>  */
    /*  START Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<SequentialBlock: name=Unit_Delay_Derivative>  */
    _state_->Unit_Delay_Derivative_memory_1 = Divide2;
    /*  END Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=User-defined Derivative>/<SequentialBlock: name=Unit_Delay_Derivative>  */
    /*  START Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator>  */
    _state_->Unit_Delay_Integrator_memory_1 = Add;
    /*  END Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator>  */
    /*  START Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator1>  */
    _state_->Unit_Delay_Integrator1_memory_1 = Divide1;
    /*  END Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=Controller_phi>/<SystemBlock: name=Intergrator_Trapezoidal>/<SequentialBlock: name=Unit_Delay_Integrator1>  */
}

