/*
    PID_phi.pde
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 25/02/2015 16:31:51.529
    source model: PIDcontroller
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "PID_phi.h"

/* Function definitions */

void PID_phi_init(t_PIDcontroller_state *_state_) {
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=u_prev>  */
    _state_->u_prev_memory_3 = 0;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=u_prev>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=y_prev>  */
    _state_->y_prev_memory_2 = 0;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=y_prev>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<SequentialBlock: name=u_prev>  */
    _state_->u_prev_memory_4 = 0;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<SequentialBlock: name=u_prev>  */
}

void PID_phi_compute(t_PID_phi_io *_io_, t_PIDcontroller_state *_state_) {
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=dt>/<OutDataPort: name=>  */
    GAREAL dt;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=u>/<OutDataPort: name=>  */
    GAREAL u;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=Kp>/<OutDataPort: name=>  */
    GAREAL Kp;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=Ki>/<OutDataPort: name=>  */
    GAREAL Ki;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=Kd>/<OutDataPort: name=>  */
    GAREAL Kd;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide_4;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Divide1>/<OutDataPort: name=>  */
    GAREAL Divide1;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Divide2>/<OutDataPort: name=>  */
    GAREAL Divide2;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide_3;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<CombinatorialBlock: name=Subtract1>/<OutDataPort: name=>  */
    GAREAL Subtract1;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<SequentialBlock: name=u_prev>/<OutDataPort: name=>  */
    GAREAL u_prev_4;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<CombinatorialBlock: name=Multiply>/<OutDataPort: name=>  */
    GAREAL Multiply;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<CombinatorialBlock: name=add_u_u_prev>/<OutDataPort: name=>  */
    GAREAL add_u_u_prev;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SourceBlock: name=half>/<OutDataPort: name=>  */
    GAREAL half;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=u_prev>/<OutDataPort: name=>  */
    GAREAL u_prev_3;
    /*  Output from <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=y_prev>/<OutDataPort: name=>  */
    GAREAL y_prev;
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=dt>  */
    dt = _io_->dt;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=dt>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SourceBlock: name=half>  */
    half = 0.5;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SourceBlock: name=half>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=u>  */
    u = _io_->u;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=u>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=u_prev>  */
    u_prev_3 = _state_->u_prev_memory_3;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=u_prev>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=y_prev>  */
    y_prev = _state_->y_prev_memory_2;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=y_prev>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=Kp>  */
    Kp = _io_->Kp;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=Kp>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Divide>  */
    Divide_4 = u * Kp;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<SequentialBlock: name=u_prev>  */
    u_prev_4 = _state_->u_prev_memory_4;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<SequentialBlock: name=u_prev>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=Ki>  */
    Ki = _io_->Ki;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=Ki>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Divide1>  */
    Divide1 = Divide_4 * Ki;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Divide1>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<CombinatorialBlock: name=add_u_u_prev>  */
    add_u_u_prev = Divide1 + u_prev_3;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<CombinatorialBlock: name=add_u_u_prev>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<CombinatorialBlock: name=Multiply>  */
    Multiply = dt * half * add_u_u_prev;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<CombinatorialBlock: name=Multiply>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<CombinatorialBlock: name=Add>  */
    Add = Multiply + y_prev;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=Kd>  */
    Kd = _io_->Kd;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SourceBlock: name=Kd>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Divide2>  */
    Divide2 = Divide_4 * Kd;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Divide2>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<CombinatorialBlock: name=Subtract1>  */
    Subtract1 = Divide2 - u_prev_4;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<CombinatorialBlock: name=Subtract1>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<CombinatorialBlock: name=Divide>  */
    Divide_3 = Subtract1 / dt;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Sum>  */
    Sum = Divide_4 + Add + Divide_3;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SinkBlock: name=y>  */
    _io_->y = Sum;
    /*  END Block: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SinkBlock: name=y>  */
    /*  START Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<SequentialBlock: name=u_prev>  */
    _state_->u_prev_memory_4 = Divide2;
    /*  END Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Derivative>/<SequentialBlock: name=u_prev>  */
    /*  START Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=y_prev>  */
    _state_->y_prev_memory_2 = Add;
    /*  END Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=y_prev>  */
    /*  START Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=u_prev>  */
    _state_->u_prev_memory_3 = Divide1;
    /*  END Block memory write: <SystemBlock: name=PIDcontroller>/<SystemBlock: name=PID_phi>/<SystemBlock: name=Intergrator>/<SequentialBlock: name=u_prev>  */
}

