/*
    IB_ga_final.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 11/06/2015 15:52:23.050
    source model: IB_ga_final
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "IB_Controller.h"

/* Variable definitions */

t_X_POSITION_CONTROL_IB_io _X_POSITION_CONTROL_IB_io;
t_Y_POSITION_CONTROL_IB1_io _Y_POSITION_CONTROL_IB1_io;
t_ATTITUDE_CONTROL_IB_io _ATTITUDE_CONTROL_IB_io;
GAUINT8 i1_2;

/* Function definitions */

void IB_ga_final_init(t_IB_ga_final_state *_state_) {
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>  */

    X_POSITION_CONTROL_IB_init(_state_);
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>  */
    Y_POSITION_CONTROL_IB1_init(_state_);
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ATTITUDE CONTROL\nIB>  */
    ATTITUDE_CONTROL_IB_init(_state_);
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ATTITUDE CONTROL\nIB>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_1 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_1 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_2 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_3 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_4 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_2 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_3 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_4 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_5 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay>  */
    for (i1_2 = 0; i1_2 < 4; i1_2++) {
        _state_->Unit_Delay_memory[i1_2] = 0;
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay>  */
}

void IB_ga_final_compute(t_IB_ga_final_io *_io_, t_IB_ga_final_state *_state_) {
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=z>/<OutDataPort: name=>  */
    GAREAL z_0;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=angles>/<OutDataPort: name=>  */
    GAREAL angles[6];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=zd>/<OutDataPort: name=>  */
    GAREAL zd;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=x>/<OutDataPort: name=>  */
    GAREAL x;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=xd>/<OutDataPort: name=>  */
    GAREAL xd;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=psid>/<OutDataPort: name=>  */
    GAREAL psid;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=y>/<OutDataPort: name=>  */
    GAREAL y;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=yd>/<OutDataPort: name=>  */
    GAREAL yd;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=t>/<OutDataPort: name=>  */
    GAREAL t;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SourceBlock: name=omgs>/<OutDataPort: name=>  */
    GAREAL omgs[4];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ATTITUDE CONTROL\nIB>/<OutDataPort: name=U2>  */
    GAREAL ATTITUDE_CONTROL_IB_U2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ATTITUDE CONTROL\nIB>/<OutDataPort: name=U3>  */
    GAREAL ATTITUDE_CONTROL_IB_U3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ATTITUDE CONTROL\nIB>/<OutDataPort: name=U4>  */
    GAREAL ATTITUDE_CONTROL_IB_U4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Mux>/<OutDataPort: name=>  */
    GAREAL Mux_2[2];
    /*  Output from <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Mux1>/<OutDataPort: name=>  */
    GAREAL Mux1_2[6];
    /*  Output from <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Subtract>/<OutDataPort: name=>  */
    GAREAL Subtract;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay>/<OutDataPort: name=>  */
    GAREAL Unit_Delay[4];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<OutDataPort: name=thetad>  */
    GAREAL X_POSITION_CONTROL_IB_thetad;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<OutDataPort: name=phid>  */
    GAREAL Y_POSITION_CONTROL_IB1_phid;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL e7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL e8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL phi;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL theta;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux>/<OutDataPort: name=>  */
    GAREAL Mux_1[3];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux1>/<OutDataPort: name=>  */
    GAREAL Mux1_1[6];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain5>/<OutDataPort: name=>  */
    GAREAL Gain5_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain6>/<OutDataPort: name=>  */
    GAREAL zddot_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL Sum1_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain5>/<OutDataPort: name=>  */
    GAREAL Gain5_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain6>/<OutDataPort: name=>  */
    GAREAL zddotdot;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL Sum1_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain5>/<OutDataPort: name=>  */
    GAREAL Gain5_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain6>/<OutDataPort: name=>  */
    GAREAL Gain6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL Sum1_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL U1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL X4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld1>/<OutDataPort: name=>  */
    GAREAL _1_c7_2_ld1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld4>/<OutDataPort: name=>  */
    GAREAL _1_c7_2_ld4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product3>/<OutDataPort: name=>  */
    GAREAL Product3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction>/<OutDataPort: name=>  */
    GAREAL Trigonometric_Function;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction1>/<OutDataPort: name=>  */
    GAREAL Trigonometric_Function1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7+c8>/<OutDataPort: name=>  */
    GAREAL c7_c8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7^2>/<OutDataPort: name=>  */
    GAREAL c7_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld1>/<OutDataPort: name=>  */
    GAUINT8 ld1_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld2>/<OutDataPort: name=>  */
    GAREAL ld2_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld3>/<OutDataPort: name=>  */
    GAREAL ld3_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld4>/<OutDataPort: name=>  */
    GAREAL ld4_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld5>/<OutDataPort: name=>  */
    GAREAL ld5_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld6>/<OutDataPort: name=>  */
    GAREAL ld6_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u4*(1-c7^2+ld4)>/<OutDataPort: name=>  */
    GAREAL u4_1_c7_2_ld4_;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u6*(c7+c8)>/<OutDataPort: name=>  */
    GAREAL u6_c7_c8_;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant2>/<OutDataPort: name=>  */
    GAREAL Constant2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=c7*e7>/<OutDataPort: name=>  */
    GAREAL c7_e7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=ld4*X4>/<OutDataPort: name=>  */
    GAREAL ld4_X4;
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=t>  */
    t = _io_->t;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=t>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld1>  */
    ld1_4 = 1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_2 = _state_->Unit_Delay1_memory_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Subtract>  */
    Subtract = t - Unit_Delay1_2;
    if ((Subtract == 0.0) || (Subtract>1.0))
    {
        _state_->Unit_Delay1_memory_1 = t;
        return;
    }
    
    /*  END Block: <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Subtract>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope4>  */
    _state_->Scope4_memory_1 = Subtract;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    Constant = 22.36;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=angles>  */
    for (i1_2 = 0; i1_2 < 6; i1_2++) {
        angles[i1_2] = _io_->angles[i1_2];
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=angles>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Demux>  */
    Demux_2 = angles[0];
    Demux_1 = angles[1];
    Demux_3 = angles[2];
    Demux_4 = angles[3];
    Demux_5 = angles[4];
    Demux_6 = angles[5];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Mux1>  */
    Mux1_2[0] = Demux_2;
    Mux1_2[1] = Demux_1;
    Mux1_2[2] = Demux_3;
    Mux1_2[3] = Demux_4;
    Mux1_2[4] = Demux_5;
    Mux1_2[5] = Demux_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Mux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_1 = _state_->Unit_Delay2_memory_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_1 = Subtract * Unit_Delay2_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_3 = _state_->Unit_Delay2_memory_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_3 = Subtract * Unit_Delay2_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_2 = _state_->Unit_Delay2_memory_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_2 = Subtract * Unit_Delay2_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_4 = _state_->Unit_Delay2_memory_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_5 = Subtract * Unit_Delay2_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant1>  */
    Constant1_2 = 0.01;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_1 = _state_->Unit_Delay1_memory_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    Add_2 = Product_2 + Unit_Delay1_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_3 = _state_->Unit_Delay1_memory_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    Add_1 = Product_1 + Unit_Delay1_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_4 = _state_->Unit_Delay1_memory_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    Add_3 = Product_3 + Unit_Delay1_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_5 = _state_->Unit_Delay1_memory_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    X4 = Product_5 + Unit_Delay1_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=x>  */
    x = _io_->x;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=x>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope5>  */
    _state_->Scope5_memory_1 = x;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld3>  */
    ld3_1 = ld4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=xd>  */
    xd = _io_->xd;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=xd>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant1>  */
    Constant1_1 = c7;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld4>  */
    ld4_1 = c7;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7^2>  */
    c7_2 = ld4_1 * ld4_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7^2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld4>  */
    _1_c7_2_ld4 = ld1_4 - c7_2 + ld3_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld5>  */
    ld5_1 = c8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7+c8>  */
    c7_c8 = ld4_1 + ld5_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7+c8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant2>  */
    Constant2 = ld4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=z>  */
    z_0 = _io_->z;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=z>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>  */
    Sum1_3 = z_0 - Add_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain6>  */
    Gain6 = (double) 1 / Tca3 * Sum1_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain6>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain5>  */
    Gain5_3 = (double) 1 / Tca3 * Sum1_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=psid>  */
    psid = _io_->psid;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=psid>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld2>  */
    ld2_1 = 9.81;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld6>  */
    ld6_1 = m;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld6>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Mux>  */
    Mux_2[0] = Demux_2;
    Mux_2[1] = Demux_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<CombinatorialBlock: name=Mux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Demux>  */
    phi = Mux_2[0];
    theta = Mux_2[1];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay>  */
    for (i1_2 = 0; i1_2 < 4; i1_2++) {
        Unit_Delay[i1_2] = _state_->Unit_Delay_memory[i1_2];
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=zd>  */
    zd = _io_->zd;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=zd>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    Sum1_2 = zd - Add_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain6>  */
    zddot_2 = (double) 1 / Tca1 * Sum1_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain6>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain5>  */
    Gain5_2 = (double) 1 / Tca1 * Sum1_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    Sum1_1 = zddot_2 - Add_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain6>  */
    zddotdot = (double) 1 / Tca2 * Sum1_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain6>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain5>  */
    Gain5_1 = (double) 1 / Tca2 * Sum1_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add>  */
    e7 = zd - z_0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux>  */
    Mux_1[0] = e7;
    Mux_1[1] = zddot_2;
    Mux_1[2] = X4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>  */
    Demux1_2 = Mux_1[0];
    Demux1_1 = Mux_1[1];
    Demux1_3 = Mux_1[2];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=c7*e7>  */
    c7_e7 = Demux1_2 * Constant1_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=c7*e7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=ld4*X4>  */
    ld4_X4 = Demux1_3 * Constant2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=ld4*X4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Add>  */
    Add_4 = Demux1_1 + ld4_X4 + c7_e7;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SinkBlock: name=Scope>  */
    _state_->Scope_memory_1 = Add_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SinkBlock: name=Scope>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add1>  */
    e8 = Add_4 - Gain6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux1>  */
    Mux1_1[0] = phi;
    Mux1_1[1] = theta;
    Mux1_1[2] = zddotdot;
    Mux1_1[3] = e7;
    Mux1_1[4] = e8;
    Mux1_1[5] = X4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>  */
    Demux_7 = Mux1_1[0];
    Demux_8 = Mux1_1[1];
    Demux_9 = Mux1_1[2];
    Demux_10 = Mux1_1[3];
    Demux_11 = Mux1_1[4];
    Demux_12 = Mux1_1[5];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction>  */
    Trigonometric_Function = cos(Demux_7);
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction1>  */
    Trigonometric_Function1 = cos(Demux_8);
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product1>  */
    Product1_1 = Trigonometric_Function * Trigonometric_Function1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u4*(1-c7^2+ld4)>  */
    u4_1_c7_2_ld4_ = _1_c7_2_ld4 * Demux_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u4*(1-c7^2+ld4)>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product2>  */
    Product2 = ld4_1 * ld3_1 * Demux_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u6*(c7+c8)>  */
    u6_c7_c8_ = c7_c8 * Demux_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u6*(c7+c8)>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    _1_c7_2_ld1 = u4_1_c7_2_ld4_ + u6_c7_c8_ - Product2 + Demux_9 + ld2_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product3>  */
    Product3 = ld6_1 * _1_c7_2_ld1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Divide>  */
    Divide = 1.0 / Product1_1 * Product3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4 = Divide > Constant;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    Product_4 = Relational_Operator4 * Constant;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5 = Divide < Constant1_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    Product1_2 = Relational_Operator5 * Constant1_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    Add2 = Product_4 + Product1_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    if (Add2 != 0) {
        U1 = Add2;
    } else {
        U1 = Divide;
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope2>  */
    _state_->Scope2_memory_1 = U1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=U1>  */
    _io_->U1 = U1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=U1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>  */
    _X_POSITION_CONTROL_IB_io.U1 = U1;
    _X_POSITION_CONTROL_IB_io.x = x;
    _X_POSITION_CONTROL_IB_io.xd = xd;
    _X_POSITION_CONTROL_IB_io.dt = Subtract;
    X_POSITION_CONTROL_IB_compute(&_X_POSITION_CONTROL_IB_io, _state_);
    X_POSITION_CONTROL_IB_thetad = _X_POSITION_CONTROL_IB_io.thetad;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=omgs>  */
    for (i1_2 = 0; i1_2 < 4; i1_2++) {
        omgs[i1_2] = _io_->omgs[i1_2];
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=omgs>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=y>  */
    y = _io_->y;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=y>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope1>  */
    _state_->Scope1_memory_2 = U1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=yd>  */
    yd = _io_->yd;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SourceBlock: name=yd>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>  */
    _Y_POSITION_CONTROL_IB1_io.U1 = U1;
    _Y_POSITION_CONTROL_IB1_io.y = y;
    _Y_POSITION_CONTROL_IB1_io.yd = yd;
    _Y_POSITION_CONTROL_IB1_io.dt = Subtract;
    Y_POSITION_CONTROL_IB1_compute(&_Y_POSITION_CONTROL_IB1_io, _state_);
    Y_POSITION_CONTROL_IB1_phid = _Y_POSITION_CONTROL_IB1_io.phid;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ATTITUDE CONTROL\nIB>  */
    for (i1_2 = 0; i1_2 < 6; i1_2++) {
        _ATTITUDE_CONTROL_IB_io.angles[i1_2] = Mux1_2[i1_2];
    }
    _ATTITUDE_CONTROL_IB_io.thetad = X_POSITION_CONTROL_IB_thetad;
    _ATTITUDE_CONTROL_IB_io.phid = Y_POSITION_CONTROL_IB1_phid;
    _ATTITUDE_CONTROL_IB_io.psid = psid;
    _ATTITUDE_CONTROL_IB_io.dt = Subtract;
    for (i1_2 = 0; i1_2 < 4; i1_2++) {
        _ATTITUDE_CONTROL_IB_io.omgs[i1_2] = Unit_Delay[i1_2];
    }
    ATTITUDE_CONTROL_IB_compute(&_ATTITUDE_CONTROL_IB_io, _state_);
    ATTITUDE_CONTROL_IB_U2 = _ATTITUDE_CONTROL_IB_io.U2;
    ATTITUDE_CONTROL_IB_U3 = _ATTITUDE_CONTROL_IB_io.U3;
    ATTITUDE_CONTROL_IB_U4 = _ATTITUDE_CONTROL_IB_io.U4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ATTITUDE CONTROL\nIB>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=U2>  */
    _io_->U2 = ATTITUDE_CONTROL_IB_U2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=U2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=U3>  */
    _io_->U3 = ATTITUDE_CONTROL_IB_U3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=U3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=U4>  */
    _io_->U4 = ATTITUDE_CONTROL_IB_U4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=U4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope3>  */
    _state_->Scope3_memory_3 = Y_POSITION_CONTROL_IB1_phid;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SinkBlock: name=Scope3>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay>  */
    for (i1_2 = 0; i1_2 < 4; i1_2++) {
        _state_->Unit_Delay_memory[i1_2] = omgs[i1_2];
    }
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_5 = X4;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_4 = Add_3;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_3 = Add_1;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_2 = Add_2;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_4 = e7;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_3 = Gain5_2;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_2 = Gain5_3;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_1 = Gain5_1;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_1 = t;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SequentialBlock: name=Unit Delay1>  */
}

