/*
    X_POSITION_CONTROL_nIB.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 11/06/2015 15:52:23.118
    source model: IB_ga_final
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "X_POSITION_CONTROL_nIB.h"

/* Function definitions */

void X_POSITION_CONTROL_IB_init(t_IB_ga_final_state *_state_) {
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_5 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_6 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_7 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_1 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_2 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_3 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_6 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_7 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_8 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_1 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_2 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_3 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_8 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_9 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
}

void X_POSITION_CONTROL_IB_compute(t_X_POSITION_CONTROL_IB_io *_io_, t_IB_ga_final_state *_state_) {
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=U1>/<OutDataPort: name=>  */
    GAREAL U1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=x>/<OutDataPort: name=>  */
    GAREAL x;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=xd>/<OutDataPort: name=>  */
    GAREAL xd;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=dt>/<OutDataPort: name=>  */
    GAREAL dt;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL Switch5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL e10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add4>/<OutDataPort: name=>  */
    GAREAL e9_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux>/<OutDataPort: name=>  */
    GAREAL Mux[3];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL thetad;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain>/<OutDataPort: name=>  */
    GAREAL Gain_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain1>/<OutDataPort: name=>  */
    GAREAL Gain1_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL xddot;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Zero-Order\nHold>/<OutDataPort: name=>  */
    GAREAL Zero_Order_Hold_2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain>/<OutDataPort: name=>  */
    GAREAL Gain_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain1>/<OutDataPort: name=>  */
    GAREAL Gain1_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL xddotdot;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Zero-Order\nHold>/<OutDataPort: name=>  */
    GAREAL Zero_Order_Hold_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain>/<OutDataPort: name=>  */
    GAREAL Gain_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain1>/<OutDataPort: name=>  */
    GAREAL Gain1_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL xdot;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Zero-Order\nHold>/<OutDataPort: name=>  */
    GAREAL Zero_Order_Hold_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAUINT8 Constant1_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant2>/<OutDataPort: name=>  */
    GAREAL Constant2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Math\nFunction>/<OutDataPort: name=>  */
    GAUINT8 Math_Function;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL X5_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem2>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem2>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide;
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_6 = _state_->Unit_Delay2_memory_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_5 = _state_->Unit_Delay2_memory_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_7 = _state_->Unit_Delay2_memory_7;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_2 = _state_->Unit_Delay7_memory_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_1 = _state_->Unit_Delay7_memory_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_3 = _state_->Unit_Delay7_memory_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain3>  */
    Gain3_1 = f_b * Unit_Delay7_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain3>  */
    Gain3_3 = f_b * Unit_Delay7_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain3>  */
    Gain3_4 = f_b * Unit_Delay7_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    Constant_2 = 0.7854/4.0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant>  */
    Constant_3 = 1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_7 = _state_->Unit_Delay1_memory_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_6 = _state_->Unit_Delay1_memory_7;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_8 = _state_->Unit_Delay1_memory_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant>  */
    Constant_5 = c9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant>  */
    Constant_4 = c9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem2>/<SourceBlock: name=Constant>  */
    Constant_6 = m;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem2>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain1>  */
    Gain1_2 = -f_a * Unit_Delay1_7;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain1>  */
    Gain1_1 = -f_a * Unit_Delay1_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain1>  */
    Gain1_3 = -f_a * Unit_Delay1_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_2 = _state_->Unit_Delay8_memory_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_1 = _state_->Unit_Delay8_memory_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_3 = _state_->Unit_Delay8_memory_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant1>  */
    Constant1_6 = ld5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant1>  */
    Constant1_5 = c10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Add2>  */
    Add2_4 = Constant_4 + Constant1_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant>  */
    Constant_1 = c9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_8 = _state_->Unit_Delay2_memory_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant1>  */
    Constant1_3 = c9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Math\nFunction>  */
    Math_Function = Constant1_3 * Constant1_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Math\nFunction>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain2>  */
    Gain2_1 = f_c * Unit_Delay8_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>  */
    Sum2_2 = Gain2_1 + Gain3_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain2>  */
    Gain2_3 = f_c * Unit_Delay8_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>  */
    Sum2_1 = Gain2_3 + Gain3_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain2>  */
    Gain2_4 = f_c * Unit_Delay8_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum2>  */
    Sum2_3 = Gain2_4 + Gain3_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>  */
    Gain2_2 = -1 * Constant_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_9 = _state_->Unit_Delay1_memory_9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=x>  */
    x = _io_->x;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=x>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    Zero_Order_Hold_3 = x;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain>  */
    Gain_3 = f_a * Zero_Order_Hold_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum>  */
    Sum_3 = Gain_3 + Gain1_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>  */
    xdot = Sum_3 - Sum2_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant1>  */
    Constant1_4 = ld5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant2>  */
    Constant2 = ld5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Add2>  */
    Add2_3 = Constant_3 - Math_Function + Constant2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=xd>  */
    xd = _io_->xd;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=xd>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    Zero_Order_Hold_2 = xd;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain>  */
    Gain_2 = f_a * Zero_Order_Hold_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>  */
    Sum_2 = Gain_2 + Gain1_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    xddot = Sum_2 - Sum2_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    Zero_Order_Hold_1 = xddot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain>  */
    Gain_1 = f_a * Zero_Order_Hold_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>  */
    Sum_1 = Gain_1 + Gain1_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    xddotdot = Sum_1 - Sum2_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add4>  */
    e9_5 = xd - x;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Product>  */
    Product_8 = Add2_3 * e9_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope1>  */
    _state_->Scope1_memory_1 = Product_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=U1>  */
    U1 = _io_->U1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=U1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem2>/<CombinatorialBlock: name=Divide>  */
    Divide = 1.0 / U1 * Constant_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem2>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope5>  */
    _state_->Scope5_memory_2 = xddot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=dt>  */
    dt = _io_->dt;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SourceBlock: name=dt>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_9 = dt * Unit_Delay2_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    X5_4 = Product_9 + Unit_Delay1_9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem1>/<CombinatorialBlock: name=Product>  */
    Product_11 = Constant_5 * Constant1_6 * X5_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux>  */
    Mux[0] = e9_5;
    Mux[1] = xddot;
    Mux[2] = X5_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Mux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux>  */
    Demux_14 = Mux[0];
    Demux_13 = Mux[1];
    Demux_15 = Mux[2];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product>  */
    Product_6 = Constant_1 * Demux_14;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product1>  */
    Product1_3 = Constant1_4 * Demux_15;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Add>  */
    Add = Product_6 + Demux_13 + Product1_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add1>  */
    e10 = Add - xdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product>  */
    Product_10 = Add2_4 * e10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope3>  */
    _state_->Scope3_memory_1 = Product_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add2>  */
    Add2_1 = Product_8 + Product_10 - Product_11 + xddotdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope>  */
    _state_->Scope_memory_2 = Product_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Product2>  */
    thetad = Divide * Add2_1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4 = thetad > Constant_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    Product_7 = Relational_Operator4 * Constant_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5 = thetad < Gain2_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    Product1_4 = Relational_Operator5 * Constant_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>  */
    Gain3_2 = -1 * Product1_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    Add2_2 = Product_7 + Gain3_2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    if (Add2_2 != 0) {
        Switch5 = Add2_2;
    } else {
        Switch5 = thetad;
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SinkBlock: name=thetad>  */
    _io_->thetad = Switch5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SinkBlock: name=thetad>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope4>  */
    _state_->Scope4_memory_2 = xdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope2>  */
    _state_->Scope2_memory_2 = xddotdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SinkBlock: name=Scope2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_9 = X5_4;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_8 = e9_5;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_3 = Unit_Delay7_3;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_2 = Unit_Delay7_1;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_1 = Unit_Delay7_2;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_8 = Unit_Delay2_7;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_7 = Unit_Delay2_5;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_6 = Unit_Delay2_6;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_3 = xdot;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_2 = xddotdot;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_1 = xddot;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_7 = Zero_Order_Hold_3;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_6 = Zero_Order_Hold_1;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_5 = Zero_Order_Hold_2;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=X POSITION CONTROL\nIB>/<SystemBlock: name=X Position Control>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
}

