/*
    Y_POSITION_CONTROL_nIB1.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 11/06/2015 15:52:23.169
    source model: IB_ga_final
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "Y_POSITION_CONTROL_nIB1.h"

/* Function definitions */

void Y_POSITION_CONTROL_IB1_init(t_IB_ga_final_state *_state_) {
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_9 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_10 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_11 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_4 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_5 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_6 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_10 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_11 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_12 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_4 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_5 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_6 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_12 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_13 = 0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
}

void Y_POSITION_CONTROL_IB1_compute(t_Y_POSITION_CONTROL_IB1_io *_io_, t_IB_ga_final_state *_state_) {
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=U1>/<OutDataPort: name=>  */
    GAREAL U1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=y>/<OutDataPort: name=>  */
    GAREAL y;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=yd>/<OutDataPort: name=>  */
    GAREAL yd_0;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=dt>/<OutDataPort: name=>  */
    GAREAL dt;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL Switch5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL e11_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL e12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux>/<OutDataPort: name=>  */
    GAREAL Mux[3];
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain>/<OutDataPort: name=>  */
    GAREAL Gain_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain1>/<OutDataPort: name=>  */
    GAREAL Gain1_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL yddotdot;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Zero-Order\nHold>/<OutDataPort: name=>  */
    GAREAL Zero_Order_Hold_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain>/<OutDataPort: name=>  */
    GAREAL Gain_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain1>/<OutDataPort: name=>  */
    GAREAL Gain1_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL yddot;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Zero-Order\nHold>/<OutDataPort: name=>  */
    GAREAL Zero_Order_Hold_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain>/<OutDataPort: name=>  */
    GAREAL Gain_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain1>/<OutDataPort: name=>  */
    GAREAL Gain1_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain2>/<OutDataPort: name=>  */
    GAREAL Gain2_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain3>/<OutDataPort: name=>  */
    GAREAL Gain3_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum>/<OutDataPort: name=>  */
    GAREAL Sum_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL Sum1;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum2>/<OutDataPort: name=>  */
    GAREAL Sum2_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>/<OutDataPort: name=>  */
    GAREAL Unit_Delay7_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>/<OutDataPort: name=>  */
    GAREAL Unit_Delay8_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Zero-Order\nHold>/<OutDataPort: name=>  */
    GAREAL Zero_Order_Hold_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_4;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_6;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_5;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAUINT8 Constant1_7;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant2>/<OutDataPort: name=>  */
    GAREAL Constant2;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Math\nFunction>/<OutDataPort: name=>  */
    GAUINT8 Math_Function;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_14;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL X6_3;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_15;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_13;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_8;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_9;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_16;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAUINT8 Constant_11;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_10;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_17;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem2>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_12;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem2>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide;
    /*  Output from <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem2>/<CombinatorialBlock: name=Gain>/<OutDataPort: name=>  */
    GAREAL Gain_7;
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_10 = _state_->Unit_Delay2_memory_9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_9 = _state_->Unit_Delay2_memory_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_11 = _state_->Unit_Delay2_memory_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_5 = _state_->Unit_Delay7_memory_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_4 = _state_->Unit_Delay7_memory_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    Unit_Delay7_6 = _state_->Unit_Delay7_memory_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain3>  */
    Gain3_5 = f_b * Unit_Delay7_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain3>  */
    Gain3_7 = f_b * Unit_Delay7_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain3>  */
    Gain3_8 = f_b * Unit_Delay7_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    Constant_8 = 0.7854/4.0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant>  */
    Constant_9 = 1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_11 = _state_->Unit_Delay1_memory_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_10 = _state_->Unit_Delay1_memory_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_12 = _state_->Unit_Delay1_memory_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=y>  */
    y = _io_->y;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=y>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    Zero_Order_Hold_6 = y;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain>  */
    Gain_6 = f_a * Zero_Order_Hold_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant>  */
    Constant_11 = c11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant>  */
    Constant_10 = c11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain1>  */
    Gain1_5 = -f_a * Unit_Delay1_11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain1>  */
    Gain1_4 = -f_a * Unit_Delay1_10;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain1>  */
    Gain1_6 = -f_a * Unit_Delay1_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum>  */
    Sum_6 = Gain_6 + Gain1_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=yd>  */
    yd_0 = _io_->yd;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=yd>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    Zero_Order_Hold_4 = yd_0;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain>  */
    Gain_4 = f_a * Zero_Order_Hold_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add>  */
    e11_5 = yd_0 - y;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>  */
    Sum_4 = Gain_4 + Gain1_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_5 = _state_->Unit_Delay8_memory_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_4 = _state_->Unit_Delay8_memory_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    Unit_Delay8_6 = _state_->Unit_Delay8_memory_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant1>  */
    Constant1_10 = ld6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem1>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem2>/<SourceBlock: name=Constant>  */
    Constant_12 = m;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem2>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem2>/<CombinatorialBlock: name=Gain>  */
    Gain_7 = -1 * Constant_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem2>/<CombinatorialBlock: name=Gain>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant1>  */
    Constant1_9 = c12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Add2>  */
    Add2_8 = Constant_10 + Constant1_9;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=U1>  */
    U1 = _io_->U1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=U1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem2>/<CombinatorialBlock: name=Divide>  */
    Divide = 1.0 / U1 * Gain_7;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem2>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant>  */
    Constant_7 = c11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_12 = _state_->Unit_Delay2_memory_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant1>  */
    Constant1_7 = c11;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Math\nFunction>  */
    Math_Function = Constant1_7 * Constant1_7;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Math\nFunction>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain2>  */
    Gain2_5 = f_c * Unit_Delay8_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>  */
    Sum2_5 = Gain2_5 + Gain3_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain2>  */
    Gain2_7 = f_c * Unit_Delay8_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>  */
    Sum2_4 = Gain2_7 + Gain3_7;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    yddot = Sum_4 - Sum2_4;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    Zero_Order_Hold_5 = yddot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Zero-Order\nHold>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain>  */
    Gain_5 = f_a * Zero_Order_Hold_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>  */
    Sum_5 = Gain_5 + Gain1_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    yddotdot = Sum_5 - Sum2_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope4>  */
    _state_->Scope4_memory_3 = yddotdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain2>  */
    Gain2_8 = f_c * Unit_Delay8_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum2>  */
    Sum2_6 = Gain2_8 + Gain3_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>  */
    Sum1 = Sum_6 - Sum2_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>  */
    Gain2_6 = -1 * Constant_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_13 = _state_->Unit_Delay1_memory_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=dt>  */
    dt = _io_->dt;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SourceBlock: name=dt>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_15 = dt * Unit_Delay2_12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    X6_3 = Product_15 + Unit_Delay1_13;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem1>/<CombinatorialBlock: name=Product>  */
    Product_17 = Constant_11 * Constant1_10 * X6_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux>  */
    Mux[0] = e11_5;
    Mux[1] = yddot;
    Mux[2] = X6_3;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Mux>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux1>  */
    Demux1_5 = Mux[0];
    Demux1_4 = Mux[1];
    Demux1_6 = Mux[2];
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product>  */
    Product_12 = Constant_7 * Demux1_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant1>  */
    Constant1_8 = ld6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product1>  */
    Product1_5 = Constant1_8 * Demux1_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Add>  */
    Add = Product_12 + Demux1_4 + Product1_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn1>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add1>  */
    e12 = Add - Sum1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product>  */
    Product_16 = Add2_8 * e12;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope3>  */
    _state_->Scope3_memory_2 = Product_16;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant2>  */
    Constant2 = ld6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<SourceBlock: name=Constant2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Add2>  */
    Add2_7 = Constant_9 - Math_Function + Constant2;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Product>  */
    Product_14 = Add2_7 * e11_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Fcn2>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope1>  */
    _state_->Scope1_memory_3 = Product_14;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add2>  */
    Add2_5 = Product_14 + Product_16 - Product_17 + yddotdot;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Product2>  */
    Product2 = Divide * Add2_5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4 = Product2 > Constant_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    Product_13 = Relational_Operator4 * Constant_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5 = Product2 < Gain2_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    Product1_6 = Relational_Operator5 * Constant_8;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>  */
    Gain3_6 = -1 * Product1_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Gain3>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    Add2_6 = Product_13 + Gain3_6;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    if (Add2_6 != 0) {
        Switch5 = Add2_6;
    } else {
        Switch5 = Product2;
    }
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SinkBlock: name=phid>  */
    _io_->phid = Switch5;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SinkBlock: name=phid>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope>  */
    _state_->Scope_memory_3 = Product_17;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope>  */
    /*  START Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope2>  */
    _state_->Scope2_memory_3 = Sum1;
    /*  END Block: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SinkBlock: name=Scope2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_13 = X6_3;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_12 = e11_5;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_6 = Unit_Delay7_6;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_5 = Unit_Delay7_4;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    _state_->Unit_Delay8_memory_4 = Unit_Delay7_5;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay8>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_12 = Unit_Delay2_11;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_11 = Unit_Delay2_9;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_10 = Unit_Delay2_10;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_6 = Sum1;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_5 = yddot;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    _state_->Unit_Delay7_memory_4 = yddotdot;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay7>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_11 = Zero_Order_Hold_6;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn3>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_10 = Zero_Order_Hold_4;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn2>/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_9 = Zero_Order_Hold_5;
    /*  END Block memory write: <SystemBlock: name=IB_ga_final>/<SystemBlock: name=Y POSITION CONTROL\nIB1>/<SystemBlock: name=Y Position Control ga>/<SystemBlock: name=Equiv_TransferFn1>/<SequentialBlock: name=Unit Delay2>  */
}

